generated: '2026-07-24'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: digital.nhs.uk
  https: true
  tls_version: TLSv1.3
  cert_expires: Sep 24 21:58:44 2026 GMT
  hsts: null
- host: api.service.nhs.uk
  https: true
  tls_version: TLSv1.2
  cert_expires: Sep 24 23:59:59 2026 GMT
  hsts: null
- host: beta.ods.dc4h.link
  https: true
  tls_version: TLSv1.2
  cert_expires: Oct  7 23:59:59 2026 GMT
  hsts: null
domains:
- domain: nhs.uk
  dnssec: false
  caa: []
  spf: true
  dmarc: true
  dmarc_policy: reject
- domain: dc4h.link
  dnssec: false
  caa: []
  spf: false
  dmarc: true
  dmarc_policy: quarantine
